build: off

branches:
  only:
    - master

# ruby versions under test
environment:
  matrix:
    - RUBY_VERSION: 24-x64

install:
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - SET LOG_SPEC_ORDER=true
  # Due to a bug in the version of OpenSSL shipped with Ruby 2.4.1 on Windows
  # (https://bugs.ruby-lang.org/issues/11033). Errors are ignored because the
  # mingw gem calls out to pacman to install OpenSSL which is already
  # installed, causing gem to raise a warning that powershell determines to be
  # a fatal error.
  - ps: |
      $ErrorActionPreference = "SilentlyContinue"
      if($env:RUBY_VERSION -eq "24-x64") {
        gem install openssl "~> 2.0.4" --no-rdoc --no-ri -- --with-openssl-dir=C:\msys64\mingw64
      }
      $host.SetShouldExit(0)
  - bundle install --jobs 4 --retry 2

before_test:
  - type Gemfile.lock
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rspec spec/beaker
